---
-  name: restart firewalld
   systemd:
    name: firewalld
    state: restarted
    enabled: yes

- name: restart nomad
  systemd: 
    name: nomad.service
    state: restarted
    enabled: yes

- name: reload nginx
  service:
    name: nginx
    state: reloaded    