--- 
- name: creating consul-template config dir
  ansible.builtin.file: 
    path: /etc/consul-template.d
    state: directory 
    mode: '0755'
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['nomad_cluster'] }}"     

- name: moving consul.hcl
  ansible.builtin.copy: 
    src: ../files/consul-template.hcl
    dest: /etc/consul.d/consul-template.hcl
    owner: root
    group: root
    mode: '0755'
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['nomad_cluster'] }}"  