---
# roles/post/tasks/sudouser.yml

- name: generate sudo user password
  set_fact:
    sudo_username_pass: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits,punctuation') }}"
  run_once: true
  delegate_to: "{{ groups['nomad_cluster'][0] }}"

- name: create sudo user
  user:
    name: "{{ sudo_username }}"
    shell: /bin/bash
    groups: sudo
    password: "{{ sudo_username_pass | password_hash('sha512') }}"
    update_password: on_create
    expires: -1
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    state: present